// This Java source file was generated on 2020-09-06 13:40:52 (Malay Peninsula Standard Time)
package io.tealight.api.oanda.v20.def.transaction;

public enum OrderFillReason {
    LIMIT_ORDER,
    STOP_ORDER,
    MARKET_IF_TOUCHED_ORDER,
    TAKE_PROFIT_ORDER,
    STOP_LOSS_ORDER,
    GUARANTEED_STOP_LOSS_ORDER,
    TRAILING_STOP_LOSS_ORDER,
    MARKET_ORDER,
    MARKET_ORDER_TRADE_CLOSE,
    MARKET_ORDER_POSITION_CLOSEOUT,
    MARKET_ORDER_MARGIN_CLOSEOUT,
    MARKET_ORDER_DELAYED_TRADE_CLOSE,
    FIXED_PRICE_ORDER,
    FIXED_PRICE_ORDER_PLATFORM_ACCOUNT_MIGRATION,
    FIXED_PRICE_ORDER_DIVISION_ACCOUNT_MIGRATION,
    FIXED_PRICE_ORDER_ADMINISTRATIVE_ACTION
}
